language: generic
install:
  - npm install -g markdown-link-validator remark-cli remark-validate-links
script:
  - "remark -u remark-validate-links -f *.md && \
  markdown-link-validator -i 'linkedin.com/in/|vimeo.com/|solid.mit.edu|gitter.im/solid/team' ."
  # linkedin profiles don't return 200s
  # vimeo links don't consistently return 200s on CI
  # gitter link is a private link and thus can't return 200
